### ISSUE TITLE
Folder naming recommendation

### ISSUE THREAD

**Issue by aminya** [idleberg/generator-atom-package-typescript#8]
Working with big projects (TS only or Mixed), I have come up with this convention for using TypeScript without changing the code:
- Make a general `tsconfog.json` that specifies general options in the root folder (shouldn't specify anything about outDir or include).

- Rename the folders that contain TypeScript by adding `_src` to the end of the original folder name. For example `lib_src` and `spec_src` for TypeScript files and `lib` and `spec` for the output and compiled JS files.
```
-root
    |
    |- lib
    |- lib_src
    |- spec
    |- spec_src 
```

- Include separate `tsconfig.json` files for each TypeScript folder using [extends](https://www.typescriptlang.org/v2/en/tsconfig#extends) feature.
For example for lib_src:
```json
{
  "extends": "../tsconfig.json",
  "outDir" : "../lib"
}
```
For example for spec_src:
```json
{
  "extends": "../tsconfig.json",
  "outDir" : "../spec"
}
```
I think this generator can follow the same procedure. This helps to inject TypeScript into the projects without changing any code or being nervous about pathing issues.

**Comment by idleberg** [comment]
This package is meant to create boilerplate packages that suit many. It doesn't keep anyone from tweaking the defaults. I would consider following patterns or conventions that are widely accepted or used, but not those of personal preference. While this package is largely influenced by my personal preferences, I try to follow conventions when there are some. 

Also, I appreciate your suggestions, but cannot accept all of them. If you prefer different defaults, you're probably best of forking this package.
